providers = ["java"]

[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Xms64m -Xmx300m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseContainerSupport -XX:MaxRAMPercentage=70.0 -Djava.security.egd=file:/dev/./urandom -jar target/*.jar --spring.profiles.active=railway --server.port=$PORT"
